spring:
  jpa:
    database: postgresql
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show_sql: true

  datasource:
    hikari:
      maximum-pool-size: 4
    url: jdbc:postgresql://localhost:5432/fc_sns
    username: postgres
    password: 1234
    database-platform: postgres
    driver-class-name: org.postgresql.Driver

jwt:
  seceret-key: fc.sns-application-2024.secret_key
  token:
    expired-time-ms: 2592000000 #30일 - 24(시간) * 60(분) * 60(초) * 30(일)
